# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import query_service_pb2 as proto_dot_query__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/query_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryServiceStub(object):
    """查询服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/query_service.QueryService/Query',
                request_serializer=proto_dot_query__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=proto_dot_query__service__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.QueryStream = channel.unary_stream(
                '/query_service.QueryService/QueryStream',
                request_serializer=proto_dot_query__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=proto_dot_query__service__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.QueryBidiStream = channel.stream_stream(
                '/query_service.QueryService/QueryBidiStream',
                request_serializer=proto_dot_query__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=proto_dot_query__service__pb2.QueryResponse.FromString,
                _registered_method=True)


class QueryServiceServicer(object):
    """查询服务定义
    """

    def Query(self, request, context):
        """一元RPC - 单轮对话
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStream(self, request, context):
        """服务器端流式RPC - 多轮对话（预留接口）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryBidiStream(self, request_iterator, context):
        """双向流式RPC - 多轮对话（预留接口）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=proto_dot_query__service__pb2.QueryRequest.FromString,
                    response_serializer=proto_dot_query__service__pb2.QueryResponse.SerializeToString,
            ),
            'QueryStream': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryStream,
                    request_deserializer=proto_dot_query__service__pb2.QueryRequest.FromString,
                    response_serializer=proto_dot_query__service__pb2.QueryResponse.SerializeToString,
            ),
            'QueryBidiStream': grpc.stream_stream_rpc_method_handler(
                    servicer.QueryBidiStream,
                    request_deserializer=proto_dot_query__service__pb2.QueryRequest.FromString,
                    response_serializer=proto_dot_query__service__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'query_service.QueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('query_service.QueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryService(object):
    """查询服务定义
    """

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/query_service.QueryService/Query',
            proto_dot_query__service__pb2.QueryRequest.SerializeToString,
            proto_dot_query__service__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/query_service.QueryService/QueryStream',
            proto_dot_query__service__pb2.QueryRequest.SerializeToString,
            proto_dot_query__service__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryBidiStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/query_service.QueryService/QueryBidiStream',
            proto_dot_query__service__pb2.QueryRequest.SerializeToString,
            proto_dot_query__service__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
